"use strict";
exports.__esModule = true;
var Punto_1 = require("./Punto");
var Recta_1 = require("./Recta");
var p1 = new Punto_1.Punto(3, 2);
var p2 = new Punto_1.Punto(1, 2);
var r1 = new Recta_1.Recta(p1, p2);
console.log(r1.toString());
console.log("largo 1 = ", r1.largo(), " cm");
r1.get_puntoFinal().set_y(9);
console.log(r1.toString());
console.log("largo 2 = ", r1.largo(), " cm");
